apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   app.xgeeks.org/team: idp_training
#   backstage.io/kubernetes-id: test-ai-standard

namespace: idp-dev
# namespace: test-ai-standard-idp_training-dev

resources:
  - ../../base
  - ingress.yaml

images:
  # ATENTION name = image.name NOT name = spec.containers[0].name
  - name: ghcr.io/xgeekshq/test-ai-standard
    newTag: v1
# replicas:
#   - name: test-ai-standard # the deployment name
#     count: 1
